name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Start Build
      run : echo "Start Build.."


  lint:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Start Build
      run : echo "Start lint.."
  test:
   runs-on: ubuntu-latest
   needs: [build,lint]
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Start Build
      run : echo "Start test.."


  deploy:
   runs-on: ubuntu-latest
   needs: [build, lint,test]

   steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Start Build
      run : echo "Start deploy.."
